name: Release

on:
    release:
        types: [published]

jobs:
    publish:
        name: Publish to npm
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4.1.4

            - name: pnpm setup
              uses: pnpm/action-setup@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  registry-url: "https://registry.npmjs.org"

            - run: pnpm install --frozen-lockfile
            - run: pnpm test
            - run: pnpm build

            - name: Publish to npm
              run: pnpm publish --access public --provenance --no-git-checks
